### ISSUE TITLE
Personal Tabs

### ISSUE THREAD

**Issue by TonyBaldascino** [xeloader/modest-guitar#2]
Suggest adding additional url pattern in **manifest.json** to enable the extension for personal tabs:

`"matches": ["*://*.ultimate-guitar.com/tab/*", "*://*.ultimate-guitar.com/user/tab/*"]`

**Comment by xeloader** [comment]
Suuure! Didn't even know that personal tabs existed until now. Is there any way for me to test this out? Can't seem to navigate myself to a link that contains `*://*.ultimate-guitar.com/user/tab`

**Comment by xeloader** [comment]
Nvm found it. Thanks for letting me know! 🎉

**Comment by xeloader** [comment]
Added you to the readme. Thanks once again.

Waiting for Google to review the extension, might take a while.
