### ISSUE TITLE
Doesn't seem to work on pro chords

### ISSUE THREAD

**Issue by aberonni** [xeloader/modest-guitar#3]
For example: https://tabs.ultimate-guitar.com/tab/adele/hello-official-1977701

I haven't checked properly yet. Might open a PR if I get around to it.

**Comment by xeloader** [comment]
What's the verdict, did it work? 🎉

**Comment by aberonni** [comment]
Still not working I'm afraid, and haven't got a chance to work on a PR yet

**Comment by xeloader** [comment]
Will update the current version on Google Play later today! Thanks for the PR, much appreciated. Added you to list of contributors as well.

✌️

**Comment by aberonni** [comment]
Awesome! Thanks for reviewing and merging so quickly 🙏

**Comment by xeloader** [comment]
No problem fam, it's live on the Chrome store now! Woop! 💪
