### ISSUE TITLE
Extension disabled and removed from store

### ISSUE THREAD

**Issue by aberonni** [xeloader/modest-guitar#5]
Looks like it violates some policy but not sure why

<img width="410" alt="image" src="https://user-images.githubusercontent.com/1260402/175922601-e4497f9f-7663-4f24-8070-10a55f7323aa.png">

**Comment by xeloader** [comment]
Looks like the permission `activeTab` wasn't used properly, so they removed it. Thank you GOOGLE.

Working on resubmitting the extension now! 🎉 

*Edit*
<img width="152" alt="image" src="https://user-images.githubusercontent.com/2003998/176136934-7e1dd9ba-c028-4494-b97d-2b0f06c48f0b.png">

🤞
